
light_color: &light_color C6CCC5ff
dark_color: &dark_color 01031Cff

bar: 
  location: top
  height: 14
  font: RecMonoLinear Nerd Font Mono:pixelsize=11:style=Regular
  layer: top
  margin: 14
  background: *dark_color
  foreground: *light_color
  spacing: 6

  border:
    top-width:    6
    bottom-width: 6
  
  left:
  - script:
      path: ~/.config/yambar/scripts/niri_workspaces.sh
      poll-interval: 250
      content:
      - string:
          text: "{pre_focused_workspaces} "
      - string:
          text: "{focused_workspace}"
          foreground: *dark_color
          deco:
            background:
              color: *light_color
      - string:
          text: " {post_focused_workspaces}"

  center: 
  - clock:
      content:
      - string: 
          text: " {time} "
          foreground: *dark_color
          deco:
            background:
              color: *light_color

  right:
  - script:
      path: ~/.config/yambar/scripts/pulseaudio.sh
      poll-interval: 250
      content:
        map:
          conditions:
            sink_muted == false:
              string:
                text: " audio: {sink_name} {sink_volume} "
                foreground: *dark_color
                deco:
                  background:
                    color: *light_color
            sink_muted == true:
              string:
                text: " audio: {sink_name} muted({sink_volume}) "
                foreground: *dark_color
                deco:
                  background:
                    color: *light_color

  - network:
      poll-interval: 1000
      content:
        map:
          conditions:
            name == wlp4s0:
              string:
                foreground: *dark_color
                deco:
                  background:
                    color: *light_color
                text: " net: {ssid} {dl-speed:mb}MB/{ul-speed:mb}MB "

  - mem:
      poll-interval: 1000
      content:
        string:
          foreground: *dark_color
          deco:
            background:
              color: *light_color
          text: " mem: {percent_used}% "

  - cpu:
      poll-interval: 1000
      content:
        map:
          conditions:
            id < 0:
              string:
                foreground: *dark_color
                deco:
                  background:
                    color: *light_color
                text: " cpu: {cpu}% "


